sset autoindent
set expandtab
set shiftround
set shiftwidth=4
set smarttab  
set tabstop=4
set hlsearch
set ignorecase
set smartcase
set encoding=utf-8
set linebreak
set scrolloff=1
set sidescrolloff=5
syntax enable
set wrap
set laststatus=2
set number
set noerrorbells
set visualbell
set mouse=a
set title
set foldmethod=indent
set nofoldenable
set history=1000
